spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/mydb
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver
#    url: jdbc:Mysql://walab.handong.edu:3306/cseeselfchecker
#    username: cseeselfchecker
#    password: kimleean
#    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: false
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace